import * as React from 'react'
import Head from 'next/head'
import ArticleList from '@/Components/ChakraAffichage/Index'
import SmallWithSocial from '@/Components/BasDePage/Index'
import SocialProfileSimple from '@/Components/Etude/Index'
import { Center, Heading } from '@chakra-ui/react'
import { ChanteurPref, JeuxVideos, SportifPref,} from '@/Components/AffichageArtiste/Index'
import WithSubnavigation from '@/Components/NavBar/Index'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <WithSubnavigation></WithSubnavigation>
          <Heading as="h1" textAlign="center" id="Presentation">Portfolio de NoP_YXN</Heading>
          <ArticleList></ArticleList>
          <Heading as="h1" textAlign="center" id="Etude">Mes études</Heading>
          <SocialProfileSimple></SocialProfileSimple>
          <Heading as="h1" textAlign="center" id="Hobbies">Mes hobbies</Heading>
          <Heading as="h1" textAlign="center" id="Musique"> La musique  </Heading>
          <ChanteurPref></ChanteurPref>
          <Heading as="h1" textAlign="center" id="JeuxVideo"> Les jeux vidéo  </Heading>
          <JeuxVideos></JeuxVideos>
          <Heading as="h1" textAlign="center" id="Sport"> Le sport  </Heading>
          <SportifPref></SportifPref>
          <SmallWithSocial></SmallWithSocial>
      </main>
    </>
  )
}